# Generated by Django 5.2.7 on 2025-10-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('age', models.IntegerField()),
                ('debt', models.FloatField()),
                ('employment_status', models.CharField(max_length=100)),
                ('loan_amount', models.FloatField()),
                ('loan_term_months', models.IntegerField()),
                ('credit_score', models.FloatField()),
                ('num_of_defaults', models.IntegerField()),
                ('employment_years', models.FloatField()),
                ('predicted_risk', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
